<?php
/**
 * @var \League\Plates\Template $v
 * @var Link[] $pageItems
 */

use Php\Presenter\Button;
use Php\Presenter\Link;

/** @var Link[] $items */
$items = [
    new Link('Home', '/'),
    new Link('Post', '/'),
    new Link('UIFaces', '/UIFacesUsers'),
];
?>
<nav id="sidebar">
    <header>
        <h1></h1>
    </header>
    <ul>
        <?php foreach ($items as $item): ?>
            <li>
                <a href="<?= $item->url ?>">
                    <?= $item->label ?>
                </a>
            </li>
        <?php endforeach ?>
    </ul>
    <?php if (!empty($pageItems)): ?>
        <hr>
        <ul>
            <?php foreach ($pageItems as $item): ?>
                <li>
                    <?php if ($item instanceof Link): ?>
                        <a href="<?= $item->url ?>">
                            <?= $item->label ?>
                        </a>
                    <?php elseif ($item instanceof Button): ?>
                        <form action="<?= $item->url ?>" method="post">
                            <input type="hidden" name="_method" value="<?= $item->httpMethod ?>">
                            <button type="submit" class="badge badge-primary"><?= $item->label ?></button>
                        </form>
                    <?php endif ?>
                </li>
            <?php endforeach ?>
        </ul>
    <?php endif ?>
</nav>
