<?php
/**
 * @var \League\Plates\Template $v
 * @var array $pageItems
 */

use Php\Presenter\Link;

/** @var Link[] $items */
$items = [
    new Link('Home', '/'),
    new Link('Post', '/'),
    new Link('UIFaces', '/UIFacesUsers'),
];
?>
<nav id="sidebar">
    <header>
        <h1></h1>
    </header>
    <ul>
        <?php foreach ($items as $item): ?>
            <li>
                <a href="<?= $item->url ?>">
                    <?= $item->label ?>
                </a>
            </li>
        <? endforeach ?>
    </ul>
</nav>
