openapi: 3.0.0
info:
  title: Sample API
  description: 'Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.'
  version: 0.0.1
  contact:
    name: mitsuru793
servers:
  - url: 'http://api.myapp.net/v1'
    description: 'Optional server description, e.g. Main (production) server'
  - url: 'http://staging-api.myapp.net'
    description: 'Optional server description, e.g. Internal staging server for testing'
paths:
  /users:
    post:
      summary: Create user
      operationId: create-user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      description: Create user
      tags:
        - users
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        name:
          type: string
        password:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - name
    Users:
      type: array
      items:
        $ref: '#/components/schemas/User'
    RankingItem:
      type: object
      required:
        - state
        - matome
      properties:
        state:
          type: integer
          description: '表示タイプ(0:Down,1:Keep,2:Up,3:New,4:PR)'
          format: int32
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
          x-enum-varnames:
            - Down
            - Keep
            - Up
            - New
            - PR
    Hoge:
      type: integer
      description: |
        まとめの公開範囲
         * `-2` - 削除
         * `-1` - 運営による非公開
         * `0` - 非公開・限定公開
         * `1` - 公開
      enum:
        - -2
        - -1
        - 0
        - 1
      x-enum-descriptions:
        - 削除
        - 運営による非公開
        - 非公開・限定公開
        - 公開
      x-enum-varnames:
        - adminDelete
        - adminPrivate
        - private
        - public
    FormData_DeviceType:
      type: integer
      description: デバイスタイプ ios(1|3)/android(2|4)
      format: int32
      enum:
        - '1'
        - '2'
        - '3'
        - '4'
