<?php
$v->layout('layouts/default')

/**
 * @var \Php\Domain\User\User|null $loginUser
 * @var \Php\Domain\Post\Post[] $posts
 * @var array $transformed
 * @var int $postsCount
 * @var \Pagerfanta\Pagerfanta $pager
 * @var string $pagerHtml
 */
?>
<div class="row">
    <h1>Posts Total: <?= $postsCount ?> Page: <?= $pager->getCurrentPage() ?> / <?= $pager->getNbPages() ?> </h1>
</div>
<div class="row">
    <form action="/seeds" method="post">
        <button type="submit" class="btn btn-primary">テーブル再生性</button>
    </form>
</div>
<div class="row">
    <?php dump($transformed) ?>
</div>
<div class="row">
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">title</th>
            <th scope="col">tags</th>
            <th scope="col">content</th>
            <th scope="col">year</th>
            <th scope="col">author</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($posts as $post): ?>
            <tr>
                <th scope="row"><?= $post->id ?></th>
                <td><a href="/posts/<?= $post->id ?>"><?= $post->title ?></a></td>
                <td><?= implode(', ', array_map(fn($tag) => $tag->name, $post->tags)) ?></td>
                <td><?= $post->content ?></td>
                <td><?= $post->year ?></td>
                <td><?= $post->author->name ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<div class="row">
    <div class="mx-auto">
        <?= $pagerHtml ?>
    </div>
</div>
