<?php
$v->layout('layouts/default')

/**
 * @var \Php\Domain\User\User|null $loginUser
 * @var \Php\Domain\Post\Post $post
 */
?>
<div class="row">
    <h1><?= $post->title ?></h1>
</div>
<div class="row">
    <p>Author: <?= $post->author->name ?></p>
</div>
<div class="row">
    <?php foreach ($post->tags as $tag): ?>
        <span class="badge badge-primary ml-1"><?= $tag->name ?></span>
    <?php endforeach ?>
</div>
<div class="row">
    <p><?= $post->content ?></p>
</div>
