<?php
/**
 * @var \League\Plates\Template $v
 * @var \Php\Domain\User\User|null $loginUser
 */
?>
<html lang="ja">
<head>
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row">
        <?php if (is_null($loginUser)): ?>
            <p>login user: non</p>
        <?php else: ?>
            <p>login user: <?= $loginUser->name ?></p>
        <?php endif ?>
    </div>
    <?= $v->section('content') ?>
</div>
</body>
</html>
