<?php
/**
 * @var \League\Plates\Template $v
 * @var \Php\Domain\User\User|null $loginUser
 */
?>
<html lang="ja">
<head>
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col">
            <p><a href="/">Home</a></p>
        </div>
        <div class="col">
            <?php $v->insert('partials/login-header') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            <?php $v->insert('partials/sidebar') ?>
        </div>
        <div class="col-10">
            <?= $v->section('content') ?>
        </div>
    </div>
</div>
</body>
</html>
